version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: ${HOSTNAME}
#    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        gitlab_rails['initial_root_password'] = ${ROOT_PASS}
        gitlab_rails['initial_shared_runners_registration_token'] = 'token'
        external_url 'http://129.168.2.242'
#        registry_external_url 'http://192.168.2.242'
    ports:
      - "8080:80"
      - "8822:22"
    volumes:
      - ./ephemeral/config/gitlab:/etc/gitlab
      - ./ephemeral/data/gitlab:/var/opt/gitlab
      - ./ephemeral/logs:/var/log/gitlab
#      - ./backups:/var/opt/gitlab/backups
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./ephemeral/config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

  register-gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: on-failure
    volumes:
      - ./ephemeral/config/gitlab-runner:/etc/gitlab-runner
    command:
      - register
      - --non-interactive
      - --locked=false
      - --run-untagged
      - --name=GitLab Runner
      - --tag-list=docker,dind
      - --executor=docker
      - --docker-image=docker:stable
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-network-mode=gitlab-default
    environment:
      - "CI_SERVER_URL=http://192.168.2.242:8080"
      - "REGISTRATION_TOKEN=token"
    depends_on:
      - gitlab
    networks:
      - gitlab

networks:
  gitlab:

