version: '3.4'
services:
  netbox:
    restart: unless-stopped
  netbox-worker:
    restart: unless-stopped
  nginx:
    restart: unless-stopped
    ports:
      - 8000:8080
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped
